urls.py
# coding=utf8
from django.conf.urls.defaults import *
from parliament.models import Member, Hansard
from parliament import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

nohouse_context = {'house_name':'Houses of the Oireachtas', }
dail_context = {'house':1,'path':'debates','title':'Dáil Debates','house_name':'Dáil Éireann',}
seanad_context = {'house':7,'path':'seanad','title':'Seanad Debates','house_name':'Seanad Éireann',}
wrans_context = {'house':3,'path':'wrans','title':'Written Answers','house_name':'Dáil Éireann',}

members_dict = { 'queryset': Member.objects.filter(left_reason="still_in_office").order_by("last_name"), 'extra_context':nohouse_context,}
tds_dict = { 'queryset': Member.objects.filter(left_reason="still_in_office",house=1).order_by("last_name"), 'extra_context':dail_context,}
senators_dict = { 'queryset': Member.objects.filter(left_reason="still_in_office",house=4).order_by("last_name"), 'extra_context':seanad_context,}

debates_dict = { 'queryset': Hansard.objects.filter(major=1,htype=10).order_by("hpos"), "date_field": "hdate", 'extra_context':dail_context,}
debates_month_dict = { 'queryset': Hansard.objects.filter(major=1,htype=10).order_by("hpos"), "date_field": "hdate","month_format":"%m", 'extra_context': {"dates":Hansard.objects.values('hdate').distinct(),"context":dail_context,} }

sendebates_dict = { 'queryset': Hansard.objects.filter(major=7,htype=10).order_by("hpos"), "date_field": "hdate",  'extra_context':seanad_context,}
sendebates_month_dict = { 'queryset': Hansard.objects.filter(major=7,htype=10).order_by("hpos"), "date_field": "hdate","month_format":"%m", 'extra_context': {"dates":Hansard.objects.values('hdate').distinct(),"context":seanad_context,} }

wrans_dict = { 'queryset': Hansard.objects.filter(major=3,htype=10).order_by("hpos"), "date_field": "hdate", 'extra_context':wrans_context,}
wrans_month_dict = { 'queryset': Hansard.objects.filter(major=3,htype=10).order_by("hpos"), "date_field": "hdate","month_format":"%m", 'extra_context': {"dates":Hansard.objects.values('hdate').distinct(),"context":wrans_context,} }


urlpatterns = patterns('',
    # Example:
    #(r'^djangowfy/', include('django-twfy.parliament.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    (r'^$', 'parliament.views.index'),
    (r'^members/$', 'django.views.generic.list_detail.object_list', members_dict),
    (r'^tds/$', 'django.views.generic.list_detail.object_list', tds_dict),
    (r'^senators/$', 'django.views.generic.list_detail.object_list', senators_dict),
    (r'^members/(?P<member_id>\d+)/$', 'parliament.views.memberdetail'),
    
    #  This one shows a debate index for Major type=1 at (eg) debates/2009/07/02
    (r'^debates/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'django.views.generic.date_based.archive_day', debates_month_dict),
    (r'^debates/(?P<year>\d{4})/(?P<month>\d{2})/$', 'django.views.generic.date_based.archive_month', debates_month_dict),
    (r'^debates/(?P<year>\d{4})/$', 'django.views.generic.date_based.archive_year', debates_dict),
    (r'^debates/(?P<epobject_id>\d+)/$', 'parliament.views.hansarddetail'),
    
    (r'^seanad/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'django.views.generic.date_based.archive_day', sendebates_month_dict),
    (r'^seanad/(?P<year>\d{4})/(?P<month>\d{2})/$', 'django.views.generic.date_based.archive_month', sendebates_month_dict),
    (r'^seanad/(?P<year>\d{4})/$', 'django.views.generic.date_based.archive_year', sendebates_dict),
    (r'^seanad/(?P<epobject_id>\d+)/$', 'parliament.views.hansarddetail'),

    (r'^wrans/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'django.views.generic.date_based.archive_day', wrans_month_dict),
    (r'^wrans/(?P<year>\d{4})/(?P<month>\d{2})/$', 'django.views.generic.date_based.archive_month', wrans_month_dict),
    (r'^wrans/(?P<year>\d{4})/$', 'django.views.generic.date_based.archive_year', wrans_dict),
    (r'^wrans/(?P<epobject_id>\d+)/$', 'parliament.views.hansarddetail'),

    (r'^expenses/expenses(?P<year>\d{4})\.xml$', 'parliament.views.expenses_xml'),

    (r'^search/$','parliament.views.search'),

)

parliament/models.py
# coding=utf8

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models
from django.utils.translation import ugettext_lazy as _

CONFIRM_STATES = (
    (0,_('No')),
    (1,_('Yes')),
)

ENTER_REASONS = (
    ('unknown',_('Unknown')),
    ('general_election',_('General Election')),
    ('by_election',_('By-election')),
    ('changed_party',_('Changed party')),
    ('reinstated',_('Reinstated')),
    ('appointed',_('Appointed')),
    ('devolution',_('Devolution')),
    ('election',_('Election')),
    ('accession',_('Accession')),
    ('regional_election',_('Regional Election')),
    ('replaced_in_region',_('Replaced in Region')),
    ('became_presiding_officer',_('Became Presiding Officer')),    
)

LEFT_REASONS = (
    ('unknown',_('Unknown')),
    ('still_in_office',_('Still in Office')),
    ('general_election',_('General Election')),
    ('general_election_standing',_('General Election (standing)')),
    ('general_election_not_standing',_('General Election (not standing)')),
    ('changed_party',_('Changed party')),
    ('died',_('Died')),
    ('declared_void',_('Declared Void')),
    ('resigned',_('Resigned')),
    ('disqualified',_('Disqualified')),
    ('became_peer',_('Became Peer')),
    ('devolution',_('Devolution')),
    ('dissolution',_('Dissolution')),
    ('retired',_('Retired')),
    ('regional_election',_('Regional Election')),
    ('became_presiding_officer',_('Became Presiding Officer')),
)

PARTIES = (
    ('FF',_(u'Fianna Fáil')),
    ('FG',_(u'Fine Gael')),
    ('LAB',_(u'Labour Party')),
    ('GRN',_(u'Green Party')),
    ('SF',_(u'Sinn Féin')),
    ('PD',_(u'Progressive Democrats')),
    ('IND',_(u'Independent')),
    ('SOC',_(u'Socialist Party')),
    ('CC',_(u'Ceann Comhairle')),
    ('IND-FF',_(u'Independent Fianna Fáil')),
)

# Likewise each of these three lists belongs in Django metamodels but they're
# here because this is how the original DB works right now

HTYPES = (
    (10,_('Section title')),
    (11,_('Subsection title')),
    (12,_('Speech')),
    (13,_('Procedural text')),
)

MAJOR = (
    (1,_('Debates')),
    (3,_('Written Answers')),
    (7,_('Seanad Debates')),
)

MINOR = (
    (1,_('Question')),
    (2,_('Answer')),
)

class Chamber(models.Model):
    name = models.CharField(max_length=255)
    class Meta:
	verbose_name = _("Chamber")
    def __unicode__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=512)
    class Meta:
	verbose_name = _("Person")
	verbose_name_plural = _("People")
    def __unicode__(self):
        return self.name
    

class Expense(models.Model):
    year = models.DateField()
    person = models.ForeignKey(Person)
    salary = models.FloatField()
    allowance = models.FloatField()
    cta = models.FloatField()
    mea = models.FloatField()
    consphone = models.FloatField()
    officegrant = models.FloatField()
    office = models.FloatField()
    ssa = models.FloatField()
    mobile = models.FloatField()
    travel = models.FloatField()
    committeetravel = models.FloatField()
    isdn = models.FloatField()
    trainingtravel = models.FloatField()
    cttee_ent = models.FloatField()
    ipu = models.FloatField()
    bpa = models.FloatField()

class Alert(models.Model):
    alert_id = models.AutoField(primary_key=True)
    email = models.CharField(max_length=765)
    criteria = models.CharField(max_length=765)
    deleted = models.IntegerField()
    registrationtoken = models.CharField(max_length=102)
    confirmed = models.IntegerField(choices=CONFIRM_STATES)
    created = models.DateTimeField()
    class Meta:
        db_table = u'alerts'
	verbose_name = _("Email Alert")
    def __unicode__(self):
        return self.email + ":  " + self.criteria


class Twfyuser(models.Model):
    user_id = models.AutoField(primary_key=True,db_column='user_id')
    firstname = models.CharField(max_length=765)
    lastname = models.CharField(max_length=765)
    email = models.CharField(max_length=765)
    password = models.CharField(max_length=102)
    lastvisit = models.DateTimeField()
    registrationtime = models.DateTimeField()
    registrationip = models.CharField(max_length=60, blank=True)
    status = models.CharField(max_length=39, blank=True)
    emailpublic = models.IntegerField(choices=CONFIRM_STATES)
    optin = models.IntegerField(choices=CONFIRM_STATES)
    deleted = models.IntegerField(choices=CONFIRM_STATES)
    postcode = models.CharField(max_length=30, blank=True)
    registrationtoken = models.CharField(max_length=72)
    confirmed = models.IntegerField(choices=CONFIRM_STATES)
    url = models.CharField(max_length=765,blank=True)
    api_key = models.CharField(unique=True, max_length=72, blank=True)
    class Meta:
        db_table = u'users'
	verbose_name = _("TWFY User")
    def __unicode__(self):
        return unicode(self.user_id) + " " + self.firstname + " " + self.lastname
	
class ApiKey(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(Twfyuser,db_column='user_id')
    api_key = models.CharField(unique=True, max_length=72)
    commercial = models.IntegerField(choices=CONFIRM_STATES)
    created = models.DateTimeField()
    disabled = models.DateTimeField(null=True, blank=True)
    reason = models.TextField()
    class Meta:
        db_table = u'api_key'
    def __unicode__(self):
        return self.api_key

class Member(models.Model):
    id = models.AutoField(primary_key=True,db_column='member_id')
    house = models.ForeignKey(Chamber,db_column='house')
    first_name = models.CharField(max_length=300, blank=True)
    last_name = models.CharField(max_length=765)
    constituency = models.CharField(max_length=300)
    party = models.CharField(choices=PARTIES,max_length=300)
    entered_house = models.DateField()
    left_house = models.DateField()
    entered_reason = models.CharField(max_length=72,choices=ENTER_REASONS)
    left_reason = models.CharField(max_length=87,choices=LEFT_REASONS)
    person_id = models.ForeignKey(Person, db_column='person_id')
    oir_personid = models.CharField(max_length=120, blank=True)
    title = models.CharField(max_length=150, blank=True)
    lastupdate = models.DateTimeField()
    class Meta:
        db_table = u'member'
    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

class Moffice(models.Model):
    moffice_id = models.AutoField(primary_key=True,db_column='moffice_id')
    dept = models.CharField(max_length=765,blank=True)
    position = models.CharField(max_length=600)
    from_date = models.DateField()
    to_date = models.DateField()
    person = models.ForeignKey(Person,db_column='person')
    source = models.CharField(max_length=765,blank=True)
    class Meta:
        db_table = u'moffice'
	verbose_name = _("Ministerial position")
        
class Hansard(models.Model):
    id = models.AutoField(primary_key=True,db_column='epobject_id')
    gid = models.CharField(unique=True, max_length=255, blank=True)
    htype = models.IntegerField(choices=HTYPES)
    speaker_id = models.ForeignKey('Member',db_column='speaker_id')
    major = models.IntegerField(choices=MAJOR)
    section_id = models.IntegerField()
    subsection_id = models.IntegerField()
    hpos = models.IntegerField()
    hdate = models.DateField()
    htime = models.TimeField(blank=True)
    source_url = models.CharField(max_length=765)
    minor = models.IntegerField(null=True, blank=True, choices=MINOR)
    created = models.DateTimeField(null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)
    colnum = models.IntegerField(null=True, blank=True)
    video_status = models.IntegerField()
    class Meta:
        db_table = u'hansard'
	verbose_name = _("Hansard object")
    def get_absolute_url(self):
        return "/debates/%i/" % self.id

    def __unicode__(self):
        return unicode(self.gid)

class Epobject(Hansard):
    epobject_id = models.OneToOneField('Hansard',db_column='epobject_id')
    raw_id_fields = ("epobject_id",)
    body = models.TextField(blank=True)
    type = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'epobject'
    def __unicode__(self):
        return unicode(self.id)

class Anonvotes(models.Model):
    epobject_id = models.OneToOneField('Hansard',db_column='epobject_id',primary_key=True)
    yes_votes = models.IntegerField()
    no_votes = models.IntegerField()
    class Meta:
        db_table = u'anonvotes'
	verbose_name = _("Anonymous vote")
    def __unicode__(self):
        return unicode(self.epobject_id)

class Uservotes(models.Model):
    user_id = models.ForeignKey('Twfyuser',db_column='user_id')
    epobject_id = models.ForeignKey('Hansard',db_column="epobject_id")
    vote = models.IntegerField()
    class Meta:
        db_table = u'uservotes'
	verbose_name = _("User vote")
    def __unicode__(self):
        return unicode(self.epobject_id)

class Indexbatch(models.Model):
    indexbatch_id = models.IntegerField(primary_key=True)
    created = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'indexbatch'
	verbose_name = _("Index batch")
	verbose_name_plural = _("Index batches")
    def __unicode__(self):
        return unicode(self.indexbatch_id)

class SearchQueryLog(models.Model):
    id = models.AutoField(primary_key=True)
    query_string = models.TextField(blank=True)
    page_number = models.IntegerField(null=True, blank=True)
    count_hits = models.IntegerField(null=True, blank=True)
    ip_address = models.TextField(blank=True)
    query_time = models.DateTimeField(null=True, blank=True)

parliament/views.py
import settings
import hansardcalendar
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render_to_response
from django.template import RequestContext, loader, Context
from django.db.models import Q
from parliament.models import Member, Hansard, Expense
from django.utils.safestring import mark_safe
from time import strftime, strptime
import sys
import re
import xapian



def index(request):
    return render_to_response('parliament/front.html',)

def memberdetail(request, member_id):
    try:
        p = Member.objects.get(pk=member_id)
    except Member.DoesNotExist:
        raise Http404
    return render_to_response('parliament/member_detail.html', {'member': p},
        context_instance=RequestContext(request))

def hansarddetail(request, epobject_id):
    try:
        parent = Hansard.objects.get(pk=epobject_id)
    except Hansard.DoesNotExist:
        raise Http404
    h = Hansard.objects.filter(Q(pk=epobject_id) | Q(section_id=epobject_id)).order_by("hpos")
    return render_to_response('parliament/hansard_detail.html', {'parent':parent, 'hansards': h, },
        context_instance=RequestContext(request))

def expenses_xml(request,year):
    response = HttpResponse(mimetype='text/xml')

    exes_data = Expense.objects.filter(year=strftime("%Y-%m-%d",strptime(year,"%Y")))

    t = loader.get_template('parliament/twfy_expenses_xml.txt')
    c = Context({
        'data': exes_data,
        'year': year,
    })
    response.write(t.render(c))
    return response

def search(request):
    searchdb = settings.XAPIAN_DB
    database = xapian.Database(searchdb)
    enquire = xapian.Enquire(database)
    if request.GET.get('s'):
        query_string = request.GET.get('s')
    else:
        query_string = ''

    response = HttpResponse(mimetype='text/html')

    qp = xapian.QueryParser()
    stemmer = xapian.Stem("english")
    qp.set_stemmer(stemmer)
    qp.set_database(database)
    qp.set_stemming_strategy(xapian.QueryParser.STEM_SOME)
    qp.set_default_op(xapian.Query.OP_AND)
    qp.add_boolean_prefix('speaker', 'S');
    qp.add_boolean_prefix('major', 'M');
    qp.add_boolean_prefix('date', 'D');
    qp.add_boolean_prefix('batch', 'B');
    qp.add_boolean_prefix('segment', 'U');
    qp.add_boolean_prefix('department', 'G');
    qp.add_boolean_prefix('party', 'P');
    qp.add_boolean_prefix('column', 'C');
    qp.add_boolean_prefix('gid', 'Q');

    query = qp.parse_query(query_string)
    
    enquire.set_query(query)
    matches = enquire.get_mset(0, 20)

    class Hit:
        pass
    
    resultset = []
    for m in matches:
        current = Hit()
        current.rank = m.rank + 1
        current.docid = m.docid
        current.path = m.document.get_data()
        current.percent = m.percent
        
        resultset.append(current)

    t = loader.get_template('parliament/search.html')
    c = Context ({
            'resultcount': matches.get_matches_estimated(),
            'results': resultset,
            
    })
    response.write(t.render(c))
    return response

templates/parliament/hansard_archive_day.html
{% extends "base.html" %}
{% load rendercalendar %}

{% block title %}Debates for {{ day|date:"l F jS Y" }}  | django-twfy{% endblock %}

{% block content %}
	<h2>{{ context.title }}</h2>
	<h3>{{ day|date:"l, F jS Y" }}</h3>
	{% if object_list %}
		<ul>
		{% for debate in object_list %}
			<li><a href="/debates/{{ debate.id }}">{{ debate.epobject.body }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
		<p>No debates are listed.</p>
	{% endif %}
{% endblock %}

{% block sidebar %}
	
{% endblock %}

templates/parliament/member_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load expenses %}
{% block title %}{{ member.first_name }} {{ member.last_name }} | django-twfy{% endblock %}


{% block content %}

<p class="printonly">This data was produced from a variety of sources.</p>

<div class="block" id="mp">
        <h4><a href="/rss/mp/{{ member.person_id.id }}.rdf"><img src="http://kildarestreet.com/images/rss.gif" alt="RSS feed" border="0" align="right"></a>{% ifequal member.left_reason "still_in_office" %}{% ifequal member.house.id 4 %}Senator {% endifequal %}{% endifequal %}{{ member.first_name }} {{ member.last_name }}{% ifequal member.left_reason "still_in_office" %}{% ifequal member.house.id 1 %} TD{% endifequal %}{% endifequal %}</h4>
	<div class="blockbody">
                <img class="portrait" alt="Photo of {{ member.first_name }} {{ member.last_name }}" src="http://www.kildarestreet.com/images/mpsL/{{ member.person_id.id }}.jpg">
                <ul class="hilites">
                        <li><strong>{% ifnotequal member.left_reason "still_in_office" %}Former {% endifnotequal %}{{ member.get_party_display }} TD for {{ member.constituency }}</strong></li>
			{% ifnotequal member.left_reason "still_in_office" %}<li><strong>Left Parliament on {{ member.left_house|date:"F jS Y" }}</strong> — {{ member.get_left_reason_display }}</li>{% endifnotequal %}
                        <!--<li>Changed party from Ceann Comhairle on 13 Oct 2009</li>
                        <li><a href="/alert/?only=1&amp;pid=217"><strong>Email me whenever John O'Donoghue speaks</strong></a> (no more than once per day)</li> -->
                </ul>
                <ul class="jumpers">
                        <!-- <li><a href="#votingrecord">Voting record</a></li> -->
                        <!-- <li><a href="#topics">Committees and topics of interest</a></li> -->
                        <li><a href="#expenses">Expenses</a></li>
                        <!-- <li><a href="#numbers">Numerology</a></li> -->
                </ul>
        </div>
</div>	

{% comment %}
<a name="votingrecord"></a>
<div class="block" id="votingrecord">
        <h4>Voting record</h4>
	<div class="blockbody">
                <p>No data to display yet.</p>
        </div>
</div>	
{% endcomment %}

{% comment %}
<a name="topics"></a>
<div class="block" id="topics">
        <h4>Committees and topics of interest</h4>
	<div class="blockbody">
                <p><em>This TD is not currently on any committee and has had no written questions answered for which we know the department or subject.</em></p>
        </div>
</div>
{% endcomment %}

{% comment %}
<a name="hansard"></a>
<div class="block" id="hansard">
        <h4><a href="/rss/mp/217.rdf"><img src="/images/rss.gif" alt="RSS feed" border="0" align="right"></a> Most recent appearances in parliament</h4>
	<div class="blockbody">
                <dl id="searchresults">
                        <dt><a href="/wrans/?id=2009-12-09.1632.0&amp;s=speaker%3A217#g1633.0.q"><strong>Written Answers &#8212; Water and Sewerage Schemes: Water and Sewerage Schemes</strong></a> <small>(9 Dec 2009)</small></dt>
                        <dd><p>&#8220;Question 202: To ask the Minister for the Environment, Heritage and Local Government  if funding will be made available in 2010 for the provision of a new sewage scheme (details supplied) in County Kerry.  [46077/09]&#8221;</p></dd>
                        <dt><a href="/wrans/?id=2009-12-09.1632.0&amp;s=speaker%3A217#g1634.0.q"><strong>Written Answers &#8212; Water and Sewerage Schemes: Water and Sewerage Schemes</strong></a> <small>(9 Dec 2009)</small></dt>
                        <dd><p>&#8220;Question 203: To ask the Minister for the Environment, Heritage and Local Government  if funding will be made available in 2010 for the provision of a new sewage scheme (details supplied) in County Kerry.  [46078/09]&#8221;</p></dd>
                        <dt><a href="/debates/?id=2009-10-13.2.0&amp;s=speaker%3A217#g3.0"><strong>Statement by An Ceann Comhairle</strong></a> <small>(13 Oct 2009)</small></dt>
                        <dd><p>&#8220;It is an accepted convention of our political system that the Ceann Comhairle should remain above political controversy.  Implied in that duty is an overriding obligation of fairness among all Members.  It was, therefore, inappropriate for me as Ceann Comhairle to respond publicly to various matters concerning costs incurred while I was Minister for Arts, Sport and Tourism.  For many people...&#8221;</p></dd>
                </dl>
                <p id="moreappear"><a href="/search/?pid=217&amp;pop=1#n4">More of John O'Donoghue's recent appearances</a></p>
                <p class="unneededprintlinks"><a href="/rss/mp/217.rdf" title="XML version of this person's recent appearances">RSS feed</a> (<a href="/help/#rss" title="An explanation of what RSS feeds are for">?</a>)</p>
	</div>
</div> 
{% endcomment %}

{% comment %}
<a name="expenses"></a>
<div class="block" id="expenses">
        <h4>Expenses</h4>
        <table class="people">
                <tr><th></th><th style="text-align: center; background-color: #9c9">Pay</th><th colspan="3" style="text-align: center; background-color: #9c9">Personal</th><th colspan="5" style="text-align: center; background-color: #9c9">Constituency-Related</th><th colspan="4" style="text-align: center; background-color: #9c9">Ex-Officio</th><th colspan="2" style="text-align: center; background-color: #9c9">Inter-Parl. Travel</th></tr>
                <tr><th>Year</th><th>Salary</th><th>Travel &amp; Subsistence</th><th>Mobile Phone</th><th>Misc Exp</th><th>Office</th><th>Grant</th><th>Phones</th><th>Travel</th><th>ISDN</th><th>Allow.</th><th>Secr.</th><th>Travel</th><th>Ents</th><th>BIPA</th><th>Other</th></tr>
                {% for expenserow in member.person_id.expense_set.all %}
                <tr class="{% cycle 'row-1' 'row-2' %}">
                        <td>{{ expenserow.year|date:"Y" }}</td>
                        <td>€{{ expenserow.salary|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.travel|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.mobile|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.mea|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.office|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.officegrant|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.consphone|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.cta|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.isdn|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.allowance|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.ssa|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.committeetravel|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.cttee_ent|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.bpa|floatformat:2|intcomma }}</td>
                        <td>€{{ expenserow.ipu|floatformat:2|intcomma }}</td>
                </tr>
                {% endfor %}
        </table>
</div>
{% endcomment %}

<a name="expenses"></a>
<div class="block" id="expenses">
        <h4>Expenses</h4>
	{% expenses member.person_id.id %}
        <p><strong><em>Note:</em></strong> there are some expenses -- most notably ones incurred by Ministers and Ministers of State -- which are charged to and reimbursed by Departments of State and
           not by the Houses of the Oireachtas.  Those figures are not yet available in sufficient detail to include in this table.</p>
</div>


{% comment %}
<a name="numbers"></a>
<div class="block" id="numbers">
        <h4>Numerology</h4>
	<div class="blockbody">
        	<p><em>Please note that numbers do not measure quality. Also, representatives may do other things not currently covered by this site.</em> (<a href="/help/#numbers">More about this</a>)</p>
                <ul>
                        <li>Has spoken in <a href="/search/?pid=217&amp;s=section%3Adebates&amp;pop=1"><strong>513 debates</strong></a> in the last year &#8212; well above average among TDs.</li>
                        <li>Has received answers to <strong>0 written questions</strong> in the last year &#8212; below average among TDs.</li>
                        <li>People have made <strong>0 comments</strong> on this TD's speeches &#8212; average among TDs.</li>
                        <li>This TD's speeches, in the printed record, are readable by an average <strong>14&ndash;15</strong> year old, going by the <a href="http://en.wikipedia.org/wiki/Flesch-Kincaid_Readability_Test">Flesch-Kincaid Grade Level</a> score.</li>
                        <li><strong>4</strong> people are tracking whenever this TD speaks &mdash; <a href="/alert/?only=1&amp;pid=217">email me whenever John O'Donoghue speaks</a>.</li>
                        <li>Has used three-word alliterative phrases (e.g. "she sells seashells") <strong>705 times</strong> in debates &#8212; well above average among TDs. <small>(<a href="/help/#numbers">Why is this here?</a>)</small></li>
		</ul>
	</div>
</div> 
{% endcomment %}

{% endblock %}